use std::{fs, path::Path};

use clap::{Arg, ArgMatches, Command};
use lmdb::{Environment, EnvironmentFlags};
use log::{error, info};

pub const COMMAND_NAME: &str = "unsparsify";
const DB_PATH: &str = "file-path";

pub fn command(display_order: usize) -> Command<'static> {
    Command::new(COMMAND_NAME)
        .display_order(display_order)
        .about(
            "Reduces the disk size of an LMDB database generated by a Casper node by removing \
            empty blocks of the sparse file.",
        )
        .arg(
            Arg::new(DB_PATH)
                .display_order(0)
                .value_name("DB_PATH")
                .required(true)
                .help("Path to LMDB database file."),
        )
}

pub fn run(matches: &ArgMatches) -> bool {
    let path = Path::new(
        matches
            .value_of(DB_PATH)
            .expect("should have file-path arg"),
    );

    let size_before = match fs::metadata(path) {
        Ok(metadata) => metadata.len(),
        Err(error) => {
            error!("Failed to get metadata for {}: {}", path.display(), error);
            return false;
        }
    };

    let _env = match Environment::new()
        .set_flags(EnvironmentFlags::WRITE_MAP | EnvironmentFlags::NO_SUB_DIR)
        .set_max_dbs(100)
        .set_map_size(1)
        .open(path)
    {
        Ok(env) => env,
        Err(error) => {
            error!("Failed to open {}: {}", path.display(), error);
            return false;
        }
    };

    let size_after = match fs::metadata(path) {
        Ok(metadata) => metadata.len(),
        Err(error) => {
            error!("Failed to get metadata for {}: {}", path.display(), error);
            return false;
        }
    };

    if size_before > size_after {
        info!(
            "Reduced size of {} from {} to {} bytes.",
            path.display(),
            size_before,
            size_after
        );
        true
    } else {
        info!(
            "Failed to reduce size of {} from {} bytes.",
            path.display(),
            size_before
        );
        false
    }
}
